# -*- coding: utf-8 -*-
"""python_programs1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aIBwxuXBnHmlG8qA_2qo5FSyZ5mbTvWi

1. User will input (3ages).Find the oldest one
"""

age1 = int(input("Enter your Age: "))
age2 = int(input("Enter your Age: "))
age3 = int(input("Enter your Age: "))

old_age = max(age1,age2,age3)
print("The Oldest age is: ", old_age)

"""2. Write a program that will convert celsius value to fahrenheit in Python

"""

celsius = float(input("Enter a celsius temparature :"))

fahrenheit = (celsius * 9/5) + 32

print("The fahrenheit temparature of the celsius value", celsius, "is", fahrenheit, "degree fahrenheit.")

"""3. User will input (2numbers).Write a program to swap the numbers"""

num1 = float(input("Enter the 1st Number: "))
num2 = float(input("Enter the 2nd Number: "))

swap = num1
num1 = num2
num2 = swap

print("After swapping:")
print("First number:", num1)
print("Second number:", num2)

"""4. Write a program that will give you the sum of 3 digits"""

digit1 = int(input("Eenter the first digit: "))
digit2 = int(input("Eenter the second digit: "))
digit3 = int(input("Eenter the third digit: "))

sum = digit1 + digit2 + digit3

print(f"The sum of {digit1}, {digit2}, and {digit3} is: {sum}")

"""5. Write a program that will reverse a four digit number.Also it checks whether
 the reverse is true.

"""

number = int(input("Enter the four digit number: "))

if 1000 <= number <= 9999:

  reverse_number = int(str(number)[::-1])

  if number == reverse_number:
    print(f"The number {number} is a palindrome.")
  else:
    print(f"The reverse of {number} is {reverse_number}.")
else:
  print("Please enter a valid four digit number.")

"""6. Write a program that will tell whether the number entered by the user is odd or even."""

number = int(input("Enter a Number: "))

if number % 2 == 0:
  print(f"The number is an even number.")
else:
  print(f"The number is an odd number.")

"""7.Write a program that will tell whether the given year is a leap year or not."""

year = int(input("Enter a year: "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")

"""8.Write a program to find the euclidean distance between two coordinates."""

import math

# Input the coordinates of the first point
x1 = float(input("Enter the x-coordinate of the first point: "))
y1 = float(input("Enter the y-coordinate of the first point: "))

# Input the coordinates of the second point
x2 = float(input("Enter the x-coordinate of the second point: "))
y2 = float(input("Enter the y-coordinate of the second point: "))

# Calculate the Euclidean distance
distance = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

# Display the result
print(f"The Euclidean distance between ({x1}, {y1}) and ({x2}, {y2}) is: {distance}")

"""9. Write a program that take a user inputr of three angles and will find out whether it can form a triangle or not."""

angle1 = int(input("Enter the first angle: "))
angle2 = int(input("Enter the second angle: "))
angle3 = int(input("Enter the third angle: "))


if angle1 + angle2 + angle3 == 180:
    print("The angles can form a triangle.")
else:
    print("The angles cannot form a triangle.")

"""10.Write a program that will take user input of cost price and selling price and determines whether its a loss or a profit"""

cost_price = float(input("Enter the cost price: "))
selling_price = float(input("Enter the selling price: "))

profit_loss = selling_price - cost_price

if profit_loss > 0:
    print(f"You made a profit of {profit_loss:.2f}.")
elif profit_loss < 0:
    print(f"You incurred a loss of {abs(profit_loss):.2f}.")
else:
    print("You broke even; there's neither a profit nor a loss.")



